import type { BudgetItem, Comment, Post } from "@/types";

export const demoPosts: Post[] = [
  {
    id: "post-1",
    title: "Revitalisasi Trotoar dan Drainase Koridor Sudirman Dimulai Mei 2026",
    slug: "revitalisasi-trotoar-drainase-sudirman",
    category: "Pembangunan",
    excerpt: "Pemerintah Kota Palembang mempercepat perbaikan pedestrian dan saluran air untuk mengurangi genangan di pusat kota.",
    content_html: "<p>Program revitalisasi koridor Sudirman difokuskan pada pelebaran trotoar, peningkatan akses difabel, dan pembenahan drainase mikro. Pekerjaan dilakukan bertahap agar aktivitas warga dan pelaku usaha tetap berjalan.</p><p>Dinas PUPR menargetkan area prioritas selesai sebelum akhir tahun anggaran 2026. Warga dapat memantau progres fisik dan realisasi anggaran melalui laman ini.</p>",
    thumbnail_url: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80",
    video_url: "https://www.youtube.com/embed/Dl2x7s4bV6A",
    budget_total: 18500000000,
    budget_realized: 9200000000,
    progress_percent: 49,
    status: "ongoing",
    published_at: "2026-05-01T08:00:00.000Z",
    author_name: "Dinas PUPR Kota Palembang",
  },
  {
    id: "post-2",
    title: "Perbaikan Jalan Lingkungan Kecamatan Seberang Ulu I Capai 86 Persen",
    slug: "perbaikan-jalan-seberang-ulu-satu",
    category: "Fasilitas",
    excerpt: "Sebanyak 12 ruas jalan lingkungan masuk tahap akhir pengaspalan dan penataan bahu jalan.",
    content_html: "<p>Perbaikan jalan lingkungan dilakukan berdasarkan laporan warga dan survei teknis lapangan. Fokus pekerjaan berada pada ruas yang menghubungkan sekolah, puskesmas, dan pasar harian.</p><p>Tim pengawas memastikan kualitas lapisan aspal sesuai spesifikasi agar umur layanan jalan lebih panjang.</p>",
    thumbnail_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    budget_total: 12300000000,
    budget_realized: 10580000000,
    progress_percent: 86,
    status: "ongoing",
    published_at: "2026-04-28T10:30:00.000Z",
    author_name: "Dinas Perkimtan Kota Palembang",
  },
  {
    id: "post-3",
    title: "Rencana Penataan Taman Kambang Iwak Masuk Konsultasi Publik",
    slug: "penataan-taman-kambang-iwak",
    category: "Pengumuman",
    excerpt: "Warga dapat memberi masukan terkait area bermain, penerangan, keamanan, dan pengelolaan sampah taman.",
    content_html: "<p>Penataan Taman Kambang Iwak masih berada pada tahap konsultasi publik. Pemerintah membuka ruang aspirasi untuk memastikan desain taman menjawab kebutuhan warga.</p><p>Masukan yang paling sering muncul akan dirangkum sebagai bahan prioritas sebelum dokumen teknis final disahkan.</p>",
    thumbnail_url: "https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&w=1200&q=80",
    budget_total: 7600000000,
    budget_realized: 820000000,
    progress_percent: 11,
    status: "planning",
    published_at: "2026-04-22T03:00:00.000Z",
    author_name: "Bappeda Kota Palembang",
  },
  {
    id: "post-4",
    title: "Peningkatan Penerangan Jalan Umum di Kawasan Pasar 16 Ilir Selesai",
    slug: "pju-pasar-16-ilir-selesai",
    category: "Anggaran",
    excerpt: "Pemasangan lampu hemat energi rampung dan mulai beroperasi untuk meningkatkan keamanan malam hari.",
    content_html: "<p>Pekerjaan PJU di Pasar 16 Ilir telah selesai dan masuk masa pemeliharaan. Lampu LED baru dipasang pada titik yang sebelumnya minim penerangan.</p><p>Evaluasi awal menunjukkan aktivitas warga pada malam hari lebih tertata dan area parkir lebih mudah diawasi.</p>",
    thumbnail_url: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1f?auto=format&fit=crop&w=1200&q=80",
    budget_total: 4800000000,
    budget_realized: 4680000000,
    progress_percent: 98,
    status: "done",
    published_at: "2026-04-18T12:00:00.000Z",
    author_name: "Dinas Perhubungan Kota Palembang",
  },
  {
    id: "post-5",
    title: "Renovasi Gedung Layanan Terpadu Kecamatan Ilir Barat II Berjalan",
    slug: "renovasi-gedung-layanan-ilir-barat-dua",
    category: "Pembangunan",
    excerpt: "Renovasi gedung layanan diarahkan untuk mempercepat pelayanan administrasi warga.",
    content_html: "<p>Renovasi mencakup ruang tunggu, loket pelayanan, sistem antrean, dan akses ramah difabel. Pekerjaan dilakukan di luar jam padat layanan untuk mengurangi gangguan.</p><p>Target utama proyek ini adalah pelayanan publik yang lebih cepat, nyaman, dan mudah diawasi.</p>",
    thumbnail_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    budget_total: 9200000000,
    budget_realized: 5100000000,
    progress_percent: 55,
    status: "ongoing",
    published_at: "2026-04-12T07:30:00.000Z",
    author_name: "Sekretariat Daerah Kota Palembang",
  },
];

export const demoBudgetItems: BudgetItem[] = [
  { id: "b1", post_id: "post-1", item_name: "Pekerjaan drainase", allocated_amount: 8500000000, realized_amount: 4100000000, description: "Pembongkaran dan pemasangan saluran baru." },
  { id: "b2", post_id: "post-1", item_name: "Trotoar dan akses difabel", allocated_amount: 6200000000, realized_amount: 3300000000, description: "Paving, guiding block, dan ramp." },
  { id: "b3", post_id: "post-2", item_name: "Pengaspalan ruas prioritas", allocated_amount: 9000000000, realized_amount: 7900000000, description: "Pekerjaan lapis aspal dan pemadatan." },
  { id: "b4", post_id: "post-3", item_name: "Desain teknis taman", allocated_amount: 1200000000, realized_amount: 320000000, description: "Kajian, desain, dan konsultasi publik." },
  { id: "b5", post_id: "post-4", item_name: "Lampu LED dan panel", allocated_amount: 4800000000, realized_amount: 4680000000, description: "Pengadaan, pemasangan, dan uji fungsi." },
  { id: "b6", post_id: "post-5", item_name: "Renovasi ruang layanan", allocated_amount: 9200000000, realized_amount: 5100000000, description: "Interior, loket, dan aksesibilitas." },
];

export const demoComments: Comment[] = [
  { id: "c1", post_id: "post-1", anonymous_name: "Warga Palembang #1428", content_raw: "Drainase di dekat halte masih sering mampet saat hujan deras.", content_filtered: "Drainase di dekat halte masih sering mampet saat hujan deras.", is_filtered: false, is_pinned: true, is_deleted: false, admin_reply: "Tim PUPR sudah menjadwalkan pengecekan tambahan minggu ini.", created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString() },
  { id: "c2", post_id: "post-1", anonymous_name: "Warga Palembang #7321", content_raw: "Tolong perhatikan akses kursi roda di depan toko lama.", content_filtered: "Tolong perhatikan akses kursi roda di depan toko lama.", is_filtered: false, is_pinned: false, is_deleted: false, created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
  { id: "c3", post_id: "post-1", anonymous_name: "Warga Palembang #8042", content_raw: "Pekerjaan malam jangan terlalu bising.", content_filtered: "Pekerjaan malam jangan terlalu bising.", is_filtered: false, is_pinned: false, is_deleted: false, created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString() },
  { id: "c4", post_id: "post-2", anonymous_name: "Warga Palembang #2219", content_raw: "Jalan dekat sekolah sudah jauh lebih baik.", content_filtered: "Jalan dekat sekolah sudah jauh lebih baik.", is_filtered: false, is_pinned: false, is_deleted: false, created_at: new Date(Date.now() - 1000 * 60 * 280).toISOString() },
  { id: "c5", post_id: "post-3", anonymous_name: "Warga Palembang #1190", content_raw: "Taman butuh lampu dan toilet yang bersih.", content_filtered: "Taman butuh lampu dan toilet yang bersih.", is_filtered: false, is_pinned: true, is_deleted: false, created_at: new Date(Date.now() - 1000 * 60 * 800).toISOString() },
  { id: "c6", post_id: "post-4", anonymous_name: "Warga Palembang #6720", content_raw: "Lampu baru membantu pedagang pulang malam.", content_filtered: "Lampu baru membantu pedagang pulang malam.", is_filtered: false, is_pinned: false, is_deleted: false, created_at: new Date(Date.now() - 1000 * 60 * 1200).toISOString() },
  { id: "c7", post_id: "post-5", anonymous_name: "Warga Palembang #4381", content_raw: "Mohon antrean layanan dibuat jelas.", content_filtered: "Mohon antrean layanan dibuat jelas.", is_filtered: false, is_pinned: false, is_deleted: false, created_at: new Date(Date.now() - 1000 * 60 * 1600).toISOString() },
];
